theme: jekyll-theme-hacker
title: Profile and Projects by TimAl6ert5
description: Following is a professional self-assesment and demonstration of my knowledge and skills in the field of computer science.  It's a work in progress (and always will be).